version: '3'

services:
  chatgpt:
    container_name: chatgpt
    image: eryajf/chatgpt-dingtalk:latest
    restart: always
    environment:
      LOG_LEVEL: "info" # 应用的日志级别 info/debug
      APIKEY: xxxxxx  # 你的 api_key
      BASE_URL: ""  # 如果你使用官方的接口地址 https://api.openai.com，则留空即可，如果你想指定请求url的地址，可通过这个参数进行配置，注意需要带上 http 协议
      MODEL: "gpt-3.5-turbo" # 指定模型，默认为 gpt-3.5-turbo , 可选参数有： "gpt-4-0314", "gpt-4", "gpt-3.5-turbo-0301", "gpt-3.5-turbo"，如果使用gpt-4，请确认自己是否有接口调用白名单
      SESSION_TIMEOUT: 600 # 会话超时时间,默认600秒,在会话时间内所有发送给机器人的信息会作为上下文
      HTTP_PROXY: http://host.docker.internal:15777 # 指定请求时使用的代理，如果为空，则不使用代理，注意需要带上 http 协议 或 socks5 协议
      DEFAULT_MODE: "单聊" # 指定默认的对话模式，可根据实际需求进行自定义，如果不设置，默认为单聊，即无上下文关联的对话模式
      MAX_REQUEST: 0 # 单人单日请求次数上限，默认为0，即不限制
      PORT: 8090 # 指定服务启动端口，默认为 8090，容器化部署时，不需要调整，一般在二进制宿主机部署时，遇到端口冲突时使用
      SERVICE_URL: ""  # 指定服务的地址，就是当前服务可供外网访问的地址(或者直接理解为你配置在钉钉回调那里的地址)，用于生成图片时给钉钉做渲染
      CHAT_TYPE: "0" # 限定对话类型 0：不限 1：只能单聊 2：只能群聊
      ALLOW_GROUPS: "" # 哪些群组可以进行对话，如果留空，则表示允许所有群组，如果要限制，则填写群组的名字，比如 "aa,bb"
      ALLOW_USERS: "" # 哪些用户可以进行对话，如果留空，则表示允许所有用户，如果要限制，则填写用户的名字，比如 "张三,李四"
      # 指定哪些人为此系统的管理员，如果留空，则表示没有人是管理员，如果要限制，则列表中写用户的userid
      # 比如 "1301691029702722,1301691029702733"，这个信息需要在钉钉管理后台的通讯录当中获取：https://oa.dingtalk.com/contacts.htm#/contacts
      # 注意：如果下边的app_secrets为空，以及使用outgoing的方式配置机器人，这两种情况下，都表示没有人是管理员
      ADMIN_USERS: ""
      APP_SECRETS: "" # 钉钉机器人在应用信息中的AppSecret，为了校验回调的请求是否合法，如果留空，将会忽略校验，则该接口将会存在其他人也能随意调用的安全隐患，因此强烈建议配置正确的secret，如果你的服务对接给多个机器人，这里可以配置多个机器人的secret，比如 "xxxx,yyyy"
      AZURE_ON: "false" # 是否走Azure OpenAi API, 默认false ,如果为true，则需要配置下边的四个参数
      AZURE_API_VERSION: "" # Azure OpenAi API 版本，比如 "2023-03-15-preview"
      AZURE_RESOURCE_NAME: "" # Azure OpenAi API 资源名称，比如 "openai"
      AZURE_DEPLOYMENT_NAME: "" # Azure OpenAi API 部署名称，比如 "openai"
      AZURE_OPENAI_TOKEN: "" # Azure token
      HELP: "欢迎使用本工具\n\n你可以查看：[用户指南](https://github.com/eryajf/chatgpt-dingtalk/blob/main/docs/userGuide.md)\n\n这是一个[开源项目](https://github.com/eryajf/chatgpt-dingtalk/)，觉得不错你可以来波素质三连." # 帮助信息，放在配置文件，可供自定义
    volumes:
      - ./data:/app/data
    ports:
      - "8090:8090"
    extra_hosts:
      - host.docker.internal:host-gateway
