version: '3'

services:
  chatgpt:
    container_name: chatgpt
    image: eryajf/chatgpt-dingtalk:latest
    restart: always
    environment:
      APIKEY: xxxxxx  # 你的 api_key
      BASE_URL: ""  # 如果你使用官方的接口地址 https://api.openai.com，则留空即可，如果你想指定请求url的地址，可通过这个参数进行配置，注意需要带上 http 协议
      MODEL: "gpt-3.5-turbo" # 指定模型，默认为 gpt-3.5-turbo , 可选参数有： "gpt-4-0314", "gpt-4", "gpt-3.5-turbo-0301", "gpt-3.5-turbo"，如果使用gpt-4，请确认自己是否有接口调用白名单
      SESSION_TIMEOUT: 600 # 会话超时时间,默认600秒,在会话时间内所有发送给机器人的信息会作为上下文
      HTTP_PROXY: http://host.docker.internal:15777 # 指定请求时使用的代理，如果为空，则不使用代理，注意需要带上 http 协议 或 socks5 协议
      DEFAULT_MODE: "单聊" # 指定默认的对话模式，可根据实际需求进行自定义，如果不设置，默认为单聊，即无上下文关联的对话模式
      MAX_REQUEST: 0 # 单人单日请求次数上限，默认为0，即不限制
      PORT: 8090 # 指定服务启动端口，默认为 8090，容器化部署时，不需要调整，一般在二进制宿主机部署时，遇到端口冲突时使用
      SERVICE_URL: ""  # 指定服务的地址，就是当前服务可供外网访问的地址(或者直接理解为你配置在钉钉回调那里的地址)，用于生成图片时给钉钉做渲染
      CHAT_TYPE: "0" # 限定对话类型 0：不限 1：只能单聊 2：只能群聊
    volumes:
      - ./data:/app/data
    ports:
      - "8090:8090"
    extra_hosts:
      - host.docker.internal:host-gateway